version: '3'
services:
  backend:
    build:
      dockerfile: ./Dockerfile
    restart: always
    command: /bin/bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
